added resources for exe - version information
codilime/contrail-controller-arch pull request #21
Opened 2017-07-18 20:02 UTC by sagarkchitnis

2017-07-21 15:31 UTC, jacek-izykowski requested changes

2017-07-21 15:31 UTC, jacek-izykowski commented on src/vnsw/agent/contrail/SConscript
> +    platform_dependent = ['windows/pkt0_interface.cc','#build/lib/windowsstubs.lib', env.RES('windows/resource.rc')]
What's going to happen when someone modifies resource.h? Shall we add resource.h to platform_dependent files?

2017-07-21 15:31 UTC, jacek-izykowski commented on src/base/logging.cc
> +        syslogident = 	boost::str( boost::format("%1%[%2%]") % ident % osspecific_getpid());
There's no `osspecific_getpid` for Linux.

2017-07-26 16:45 UTC, sagarkchitnis commented on src/vnsw/agent/contrail/SConscript
> +    platform_dependent = ['windows/pkt0_interface.cc','#build/lib/windowsstubs.lib', env.RES('windows/resource.rc')]
It is in windows directory. Specific to windows only. Only if a new resource is added,someone will need to modify it.

2017-07-26 16:47 UTC, sagarkchitnis commented on src/base/logging.cc
> +        syslogident = 	boost::str( boost::format("%1%[%2%]") % ident % osspecific_getpid());
ok. Will create a file with all these os_specific linux functions.

2017-07-27 07:27 UTC, jacek-izykowski commented on src/vnsw/agent/contrail/SConscript
> +    platform_dependent = ['windows/pkt0_interface.cc','#build/lib/windowsstubs.lib', env.RES('windows/resource.rc')]
I understand that. But do we expect that modification of resource.h should trigger some action during next compilation?

2017-07-27 07:40 UTC, sagarkchitnis commented on src/vnsw/agent/contrail/SConscript
> +    platform_dependent = ['windows/pkt0_interface.cc','#build/lib/windowsstubs.lib', env.RES('windows/resource.rc')]
Sorry I misunderstood your original question.  Yes, I just tried changing only resource.h. If you change resource.h, .rc is recompiled and the exe is re-linked.

2017-07-27 07:42 UTC, sagarkchitnis commented on src/base/logging.cc
> +        syslogident = 	boost::str( boost::format("%1%[%2%]") % ident % osspecific_getpid());
put #ifdef's for linux instead of creating new file.

2017-07-27 11:07 UTC, jacek-izykowski commented on src/vnsw/agent/contrail/SConscript
> +    platform_dependent = ['windows/pkt0_interface.cc','#build/lib/windowsstubs.lib', env.RES('windows/resource.rc')]
Ok. I just wanted to make sure that it works.

2017-08-01 13:22 UTC, closed without merging