JW-256: KSync implementation for Windows
codilime/contrail-controller-arch pull request #4
Opened 2017-04-24 14:08 UTC by jablonskim

2017-04-24 14:42 UTC, mclapinski requested changes

2017-04-24 14:42 UTC, michal-clapinski commented on src/ksync/ksync_sock.cc
> +
maybe delete this line

2017-04-24 14:42 UTC, michal-clapinski commented on src/ksync/ksync_sock.cc
> +
delete this line

2017-04-24 14:42 UTC, michal-clapinski commented on src/ksync/ksync_sock.cc
> +    pipe_.async_read_some(buf, cb);
maybe add comment with todo and task number here

2017-04-24 14:42 UTC, michal-clapinski commented on src/ksync/ksync_sock.h
> +#ifdef _WINDOWS
Maybe switch to #ifndef in headers

2017-04-24 14:42 UTC, michal-clapinski commented on src/vnsw/agent/vrouter/ksync/ksync_init.cc
> +    KSyncSock::SetNetlinkFamilyId(0);
If using `family` variable doesn't break anything then please stick with it.

2017-04-25 10:20 UTC, mclapinski approved these changes

2017-04-25 10:20 UTC, michal-clapinski commented on src/ksync/ksync_sock.cc
> +
pay more attention to that next time

2017-04-25 10:31 UTC, sodar requested changes

2017-04-25 10:31 UTC, sodar commented on src/ksync/ksync_sock.cc
> +static uint32_t GetNetlinkSeqno(char *data) {
Redundant `GetNetlinkSeqno` definitions could be removed by moving `ifdef` inside the function. What I mean is something like this:

```c
static uint32_t GetNetlinkSeqno(char *data) {
#ifndef _WINDOWS
/* original code */
#else
/* code specific to Windows */
#endif
}
```

2017-04-25 10:31 UTC, sodar commented on src/ksync/ksync_sock.cc
> +static bool NetlinkMsgDone(char *data) {
Same comment as above, regarding `GetNetlinkSeqno`.

2017-04-25 10:31 UTC, sodar commented on src/ksync/ksync_sock.cc
> +static bool ValidateNetlink(char *data) {
Same comment as above, regarding `GetNetlinkSeqno`.

2017-04-25 10:31 UTC, sodar commented on src/ksync/ksync_sock.cc
> +static void GetNetlinkPayload(char *data, char **buf, uint32_t *buf_len) {
Same comment as above, regarding `GetNetlinkSeqno`.

2017-04-25 10:31 UTC, sodar commented on src/ksync/ksync_sock.h
> +    KSyncSockNetlink(boost::asio::io_service &ios);
I think that we should leave `protocol` argument in constructor and other methods declarations. It won't be used, but less of the original code is changed this way. If compiler complains about unreferenced parameter, we could put `protocol` in some sort of `UNUSED` macro.

2017-04-25 10:31 UTC, sodar commented on src/ksync/ksync_sock.h
> +    static void Init(boost::asio::io_service &ios);
Same comment as to `KsyncSockNetlink` constructor.

2017-04-25 10:31 UTC, sodar commented on src/vnsw/agent/vrouter/ksync/ksync_init.cc
> +    KSyncSockNetlink::Init(io, NETLINK_GENERIC);
If `KsyncSockNetlink::Init` definition changes, then conditional compilation can be removed from this part.

2017-04-25 10:31 UTC, sodar commented on src/ksync/ksync_sock.cc
> +        assert(0);
I think these `asserts` are misused here. Opening the file can fail for other reasons than a programmer error (e.g. extension was not enabled). When project is compiled using release settings, assert macros are compiled to empty instructions, thus an agent will not terminate. I think `exit` or `abort` should be used here.

2017-04-25 10:31 UTC, sodar commented on src/ksync/ksync_sock.cc
> +        assert(0);
Same comment as above regarding `assert`.

2017-04-25 10:31 UTC, sodar commented on src/ksync/ksync_sock.cc
> +        assert(0);
Same comment regarding asserts.

2017-04-25 10:31 UTC, sodar commented on src/ksync/ksync_sock.cc
> +    if (ec) {
Does `send_to` throws an exception on failure? If it does, does agent code expects this exception to be thrown somewhere?

2017-04-25 10:31 UTC, sodar commented on src/ksync/ksync_sock.cc
> +        assert(0);
Same comment regardng use of `asserts`.

2017-04-25 18:53 UTC, jablonskim commented
Retest this please

2017-04-26 08:23 UTC, sodar approved these changes

2017-06-21 13:01 UTC, closed without merging