JW-1058: remove ksync_response_header
codilime/contrail-controller-arch pull request #41
Opened 2017-08-24 14:45 UTC by sodar

2017-08-24 14:48 UTC, mclapinski requested changes

2017-08-24 14:48 UTC, michal-clapinski commented on src/vnsw/agent/vrouter/ksync/ksync_init.cc
> +    KSyncSock::SetNetlinkFamilyId(WINDOWS_NETLINK_FAMILY);
Change to something platform independent like FAKE_NETLINK_FAMILY

2017-08-24 15:37 UTC, jacek-izykowski approved these changes

2017-08-24 15:58 UTC, mclapinski approved these changes

2017-08-24 16:24 UTC, sodar commented
Retest this please

2017-08-25 07:33 UTC, jacek-izykowski approved these changes

2017-08-25 08:53 UTC, merged