JW-885_test_vnswif
codilime/contrail-controller-arch pull request #44
Opened 2017-08-29 10:20 UTC by jacek-izykowski

2017-08-29 12:51 UTC, sodar requested changes

2017-08-29 12:51 UTC, sodar commented on src/ksync/test/SConscript
> +        env.Prepend(LIBS=['Dbghelp', 'windowsstubs'])
We do not have to include `Dbghelp` here, because it is already included in `MakeTestEnvFn` function.

2017-08-29 12:51 UTC, sodar commented on src/ksync/ksync_sock_user.cc
> +        nlh->nlmsg_flags &= (~NLM_F_MULTI);
Because `last_nlh` is still used in the loop before this condition, we could use it instead of manually getting last header. So old code can be used.

2017-09-01 13:35 UTC, m-kostrzewa commented
Janie, przetestuj proszę

2017-09-04 11:13 UTC, merged