JW-1002: use standard format specifiers in date parsing
codilime/contrail-controller-arch pull request #46
Opened 2017-09-04 08:48 UTC by sodar

2017-09-04 09:04 UTC, m-kostrzewa approved these changes
:D

2017-09-04 10:02 UTC, mclapinski requested changes

2017-09-04 10:02 UTC, michal-clapinski commented on src/base/autogen_util.h
> +    endp = strptime(value.c_str(), "%Y-%m-%dT%T", &tm);
add a comment in these 3 lines, so nobody changes it back

2017-09-04 10:53 UTC, mclapinski approved these changes

2017-09-05 14:06 UTC, sodar commented
Retest this please

2017-09-06 08:45 UTC, merged