Jw 914 tests
codilime/contrail-controller-arch pull request #56
Opened 2017-09-20 16:14 UTC by sodar

Test list https://gist.github.com/sodar/658e8a14d8bd1495c33352a59e105ec0

2017-09-22 08:59 UTC, jablonskim requested changes

2017-09-22 08:59 UTC, jablonskim commented on src/vnsw/agent/test-xml/test_xml.cc
> +    try {
I think that we are not allowed to use exceptions in Agent code. Additionally, I think that `fstream` by default does not throw any exception.

2017-09-22 10:10 UTC, jacek-izykowski approved these changes

2017-09-22 10:13 UTC, jablonskim approved these changes

2017-09-25 10:47 UTC, sodar commented
Retest this please

2017-09-25 10:50 UTC, sodar commented
Retest this please

2017-09-25 16:16 UTC, merged