Jw 928 agent as a service
codilime/contrail-controller-arch pull request #57
Opened 2017-09-21 15:20 UTC by PawelMarchewkaCodiLime

2017-09-21 15:37 UTC, jablonskim approved these changes

2017-09-21 15:52 UTC, mclapinski requested changes

2017-09-21 15:52 UTC, michal-clapinski commented on src/vnsw/agent/contrail/windows/service_config/service-wrapper.xml
> +    <arguments>--config_file=contrail-vrouter-agent.conf</arguments>
This is useless

2017-09-21 15:52 UTC, michal-clapinski commented on src/vnsw/agent/contrail/windows/service_config/service-wrapper.xml
> +    <description>Contrail vrouter agent</description>
I'd suggest `Contrail vRouter Agent`

2017-09-22 10:47 UTC, mclapinski requested changes

2017-09-22 10:47 UTC, michal-clapinski commented on src/vnsw/agent/contrail/windows/service_config/service-wrapper.xml
> +    <logmode>none</logmode>
please change to `append` or something

2017-09-22 12:33 UTC, mclapinski approved these changes

2017-09-25 07:47 UTC, PawelMarchewkaCodiLime commented
Janie, przetestuj, proszę.

2017-09-25 08:00 UTC, PawelMarchewkaCodiLime commented
Retest this please

2017-09-25 10:32 UTC, merged