unit test changes
codilime/contrail-controller-arch pull request #6
Opened 2017-05-10 22:10 UTC by sagarkchitnis

2017-05-11 19:07 UTC, sagarkchitnis commented
We need to have googletest-release-1.8.0.zip in the third_party folder and do “unzip -o googletest-release-1.8.0.zip” from the third_party folder.

2017-05-23 07:38 UTC, m-kostrzewa requested changes
I'm glad you got it working, but I think scons code needs some refactoring

2017-05-23 07:38 UTC, m-kostrzewa commented on src/vnsw/agent/test/test_agent_init.cc
> +				   const_cast<uint32_t&>(TestAgentInit::kIncrementalInterval)));
Some mixup with whitespaces here

2017-05-23 07:38 UTC, m-kostrzewa commented on src/vnsw/agent/test/test_pkt0_interface.h
> +        if (::bind(pkt0_client_fd_, (sockaddr *) &sin, sizeof(sin)) == -1) {
I'm not sure why the `::` are here?..

2017-05-23 07:38 UTC, m-kostrzewa commented on lib/gunit/SConscript
> +    cmd = 'copy ' + Dir('.').srcnode().abspath + '\msvc15\* ' + Dir(gtest_path).abspath + '\msvc /y'
I'm not sure why we're not using shutil.copytree here? https://docs.python.org/2/library/shutil.html#shutil.copytree

2017-05-23 07:38 UTC, m-kostrzewa commented on lib/gunit/SConscript
> +    subprocess.call("devenv gtest.sln /Build", shell=True)
As far as I know scons recommends using env.Command() instead of subprocess http://scons.org/doc/2.0.1/HTML/scons-user/c3762.html

2017-05-23 07:38 UTC, m-kostrzewa commented on lib/gunit/SConscript
> +    fromfile = os.path.join(Dir(gtest_path).abspath , 'msvc','gtest', '{direct}'.format(direct='Debug' if env['TARGET_CONFIG'] =='debug' else 'Release'),  gtestlibname)
Hmm, maybe we should `os.path.join()` for setting `cmd` variable a couple lines earlier also?

2017-06-01 17:51 UTC, sagarkchitnis commented on src/vnsw/agent/test/test_agent_init.cc
> +				   const_cast<uint32_t&>(TestAgentInit::kIncrementalInterval)));
ok. Will remove extra white spaces.

2017-06-01 17:52 UTC, sagarkchitnis commented on src/vnsw/agent/test/test_pkt0_interface.h
> +        if (::bind(pkt0_client_fd_, (sockaddr *) &sin, sizeof(sin)) == -1) {
there is a bind function in the boost library. The compiler complained of the conflict IIRC.

2017-06-01 17:52 UTC, sagarkchitnis commented on lib/gunit/SConscript
> +    cmd = 'copy ' + Dir('.').srcnode().abspath + '\msvc15\* ' + Dir(gtest_path).abspath + '\msvc /y'
in copytree, the destination directory must not exist. Here it exists.

2017-06-01 17:55 UTC, sagarkchitnis commented on lib/gunit/SConscript
> +    subprocess.call("devenv gtest.sln /Build", shell=True)
Yes, I tried that initially. However (1) env.Command creates a command target, does not execute it by default unless the target is needed (2) The shell=True seemed to be essential in similar cases.

2017-06-01 17:56 UTC, sagarkchitnis commented on lib/gunit/SConscript
> +    fromfile = os.path.join(Dir(gtest_path).abspath , 'msvc','gtest', '{direct}'.format(direct='Debug' if env['TARGET_CONFIG'] =='debug' else 'Release'),  gtestlibname)
agree. I will change it.

2017-06-12 21:03 UTC, sagarkchitnis commented
I think this can be merged now. Please let me know if any more changes are needed.

2017-06-13 09:07 UTC, jablonskim approved these changes

2017-06-13 13:13 UTC, merged