JW-1178 Agent autorestart
codilime/contrail-controller-arch pull request #70
Opened 2017-10-12 15:48 UTC by katrybacka

2017-10-18 08:24 UTC, kaweue requested changes

2017-10-18 08:24 UTC, PawelMarchewkaCodiLime commented on src/vnsw/agent/contrail/SConscript
> +    env.Append(WIXCANDLEFLAGS = ['-ext', 'WixUtilExtension.dll'])
Is it required to add WixUtilExtension.dll to candle flags ?

2017-10-18 08:24 UTC, PawelMarchewkaCodiLime commented on src/vnsw/agent/contrail/windows/msi/agent_msi.wxs
> +                                <util:ServiceConfig
Why didn't you use ServiceConfigFailureActions ? I think it doesn't require util extension.

2017-10-18 10:54 UTC, kaweue approved these changes

2017-10-19 13:07 UTC, jacek-izykowski approved these changes

2017-10-19 14:31 UTC, merged