[WIP] JW-1335 src/ifmap cleanup
codilime/contrail-controller-arch pull request #92
Opened 2017-12-11 15:55 UTC by katrybacka

2017-12-15 15:05 UTC, jablonskim approved these changes

2017-12-15 15:26 UTC, mclapinski requested changes

2017-12-15 15:26 UTC, michal-clapinski commented on src/ifmap/ifmap_agent_table.cc
> +        assert(right_it != right_list->end());
It was my change, change it back

2017-12-18 16:24 UTC, mclapinski approved these changes

2017-12-20 13:29 UTC, merged